USE eSportsTeam;

#Teamspieler mind. 2 Platz
SELECT SPIELER.VNAME, SPIELER.NNAME, PLATZ, TEAM.TEAMNAME, TEAM.SPIEL, TEAMTURNIER.NAME
FROM SPIELER, TEAMTURNIER, TEAM
WHERE SPIELER.TEAMNAME = TEAM.TEAMNAME
  AND TEAM.TEAMNAME = TEAMTURNIER.TEAMNAME
  AND TEAMTURNIER.PLATZ <= 2;

# Spieler in besonderem Haus
SELECT SPIELER.VNAME, SPIELER.NNAME, SPIELER.HAUSNAME
FROM SPIELER
WHERE
      HAUSNAME = 'Tempel der Liebe';
